=== diodeinc/edatasheets.github.io/part-spec/component.json
{
    "$id": "https://github.com/edatasheets/edatasheets.github.io/blob/main/part-spec/component.json",
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "type": "object",
    "title": "component",
    "required": [
        "componentID"
    ],
    "properties": {
        "componentID": {
            "description": "methods for identifying the version of the electronic datasheet",
            "$ref": "./common/componentID.json#/componentID"
        },
        "coreProperties": {
            "description": "core component properties as defined by the specific component spec file",
            "$ref": "./common/coreProperties.json#/coreProperties"
        },
        "pins": {
            "description": "array of pin objects with associated properties",
            "type": "array",
            "items": {
                "$ref": "./common/pinSpec.json#/pinSpec"
            }
        },
        "package": {
            "description": "component package information",
            "$ref": "./common/package.json#/package"
        },
        "register": {
            "description": "register information",
            "$ref": "./common/register.json#/register"
        },
        "thermal": {
            "description": "component temperature and thermal resistance information",
            "$ref": "./common/thermal.json#/thermal"
        },
        "componentPropertyExternalFiles": {
            "description": "external files that describe key component properties. External files can be used in lieu of defining core properties, pins, and package information in the same file",
            "$ref": "./common/externalFileMap.json#/externalFileMap"
        },
        "additionalSpecExternalFiles": {
            "description": "external files that contain information outside of the json spec. Examples include layout, simulation, etc.",
            "type": "array",
            "items": {
                "$ref": "./common/externalFile.json#/externalFile"
            }
        },
        "reliability": {
            "description": "reliability information about the component",
            "$ref": "./common/reliability.json#/reliability"
        },
        "powerSequence": {
            "description": ". list of power sequence conditions that apply to a component",
            "type": "array",
            "items": {
                "$ref": "./common/powerSequence.json#/powerSequence"
            }
        }
    },
    "additionalProperties": false
}

=== diodeinc/edatasheets.github.io/examples/reliability/capacitor_reliability_example.json
{
    "componentID": {
        "partType": "capacitor",
        "manufacturer": "global_reliability_example",
        "componentName": "capacitor_reliability_example",
        "orderableMPN": [
            "GRC01"
        ],
        "sourceDatasheetID": {
            "publishedDate": "2000-01-01 00:00:00",
            "version": "1.0",
            "datasheetURI": "www.reliabily_example_grc.com",
            "productURI": "www.global_reliability_example_grc01.com"
        },
        "digitalDatasheetID": {
            "publishedDate": "2024-10-31 00:00:00",
            "eDatasheetSpecRevision": "1.0"
        },
        "status": "end-of-life"
    },
    "coreProperties": {
        "dielectric": "ceramic",
        "value": {
            "values": [
                {
                    "typValue": 4.7,
                    "siUnit": "nanofarad"
                }
            ]
        },
        "tolerance": {
            "values": [
                {
                    "typValue": 10.0,
                    "siUnit": "percentage"
                }
            ]
        },
        "ratedVoltage": {
            "values": [
                {
                    "siUnit": "volt",
                    "maxValue": 100.0
                }
            ]
        },
        "equivalentSeriesResistance": {
            "values": [
                {
                    "typValue": 10.0,
                    "siUnit": "milliohm"
                }
            ]
        },
        "minTemperature": {
            "values": [
                {
                    "siUnit": "celsius",
                    "minValue": -55.0
                }
            ]
        },
        "maxTemperature": {
            "values": [
                {
                    "siUnit": "celsius",
                    "maxValue": 125.0
                }
            ]
        },
        "partType": "capacitor"
    },
    "reliability": {
        "failuresInTime": {
            "values": [
                {
                    "typValue": 0.2,
                    "unitName": "FITs",
                    "conditions": [
                        "10000 components tested",
                        "1000000 operating hours"
                    ]
                    
                }
            ]
        },
        "meanTimeToFail": {
            "values": [
                {
                    "typValue": 5000000,
                    "unitName": "hours"
                }
            ]
        }
    },
    "package": {
        "length": {
            "values": [
                {
                    "typValue": 4.5,
                    "siUnit": "millimeter",
                    "minValue": 4.2,
                    "maxValue": 4.8
                }
            ]
        },
        "width": {
            "values": [
                {
                    "typValue": 3.2,
                    "siUnit": "millimeter",
                    "minValue": 3.0,
                    "maxValue": 3.4
                }
            ]
        },
        "height": {
            "values": [
                {
                    "typValue": 1.9,
                    "siUnit": "millimeter",
                    "minValue": 1.7,
                    "maxValue": 2.1
                }
            ]
        },
        "standardPackageSize": "1812"
    }
}
